GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjdmNjJhOTEzODZmNjU2MjhmNDEwOWQiLCJpYXQiOjE2MDg2NTk0NTYsImV4cCI6MTYwODY1OTQ4Nn0.xYobqqVnux-zi4AcL8K0gRPZ160GUZugHZ0u8BlxiLM

###

POST http://localhost:3000/api/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjdmNjJhOTEzODZmNjU2MjhmNDEwOWQiLCJpYXQiOjE2MDg2NTk0NTYsImV4cCI6MTYwODY1OTQ4Nn0.xYobqqVnux-zi4AcL8K0gRPZ160GUZugHZ0u8BlxiLM",
  "refreshToken": "d19ec9f9-e128-4f01-87f3-546dc99ca19b"
}

### register
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "login": "login",
  "password": "1111"
}

###

POST http://localhost:3000/api/oauth/local
Content-Type: application/json

{
  "login": "login",
  "password": "1111"
}
